import './globals.css'
import { Barriecito } from 'next/font/google'
import Script from 'next/script'
import Navbar from './Navbar'
const inter = Barriecito({ subsets: ['latin'], weight: ["400"],})


export const metadata = {
  
  title: 'Hunting Coder',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
     
          
   
      
      
      <body className={inter.className}><Navbar/>{children}</body>
    </html>
  )
}
